In [1]:
import torch
import numpy as np

In [2]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [4]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.7514, 0.5958],
        [0.6289, 0.8093]]) 



In [5]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.3847, 0.7569, 0.6423],
        [0.7353, 0.1395, 0.3530]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [6]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [7]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    print('moving to GPU')
    tensor = tensor.to("cuda")

moving to GPU


In [8]:
tensor = torch.rand(3, 3)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([0.9043, 0.7245, 0.9336])
First column: tensor([0.9043, 0.9490, 0.1946])
Last column: tensor([0.9336, 0.4354, 0.9180])
tensor([[0.9043, 0.0000, 0.9336],
        [0.9490, 0.0000, 0.4354],
        [0.1946, 0.0000, 0.9180]])


In [9]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[0.9043, 0.0000, 0.9336, 0.9043, 0.0000, 0.9336, 0.9043, 0.0000, 0.9336],
        [0.9490, 0.0000, 0.4354, 0.9490, 0.0000, 0.4354, 0.9490, 0.0000, 0.4354],
        [0.1946, 0.0000, 0.9180, 0.1946, 0.0000, 0.9180, 0.1946, 0.0000, 0.9180]])


In [10]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
# ``tensor.T`` returns the transpose of a tensor
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)


# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[0.8177, 0.0000, 0.8716],
        [0.9006, 0.0000, 0.1896],
        [0.0379, 0.0000, 0.8427]])

In [11]:
device = (
    "cuda"
    if torch.cuda.is_available()
    else "mps"
    if torch.backends.mps.is_available()
    else "cpu"
)
print(f"Using {device} device")

Using cuda device


In [12]:
torch.backends.mps.is_available()

False

In [13]:
import os
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets, transforms


In [14]:

class NeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 10),
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

In [15]:
model = NeuralNetwork().to(device)
print(model)

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


In [16]:
X = torch.rand(1, 28, 28, device=device)
logits = model(X)
pred_probab = nn.Softmax(dim=1)(logits)
y_pred = pred_probab.argmax(1)
print(f"Predicted class: {y_pred}")

Predicted class: tensor([7], device='cuda:0')


In [17]:
input_image = torch.rand(3,28,28)
print(input_image.size())

torch.Size([3, 28, 28])


In [18]:
flatten = nn.Flatten()
flat_image = flatten(input_image)
print(flat_image.size())

torch.Size([3, 784])


In [19]:
layer1 = nn.Linear(in_features=28*28, out_features=20)
hidden1 = layer1(flat_image)
print(hidden1.size())

torch.Size([3, 20])


In [20]:
print(f"Before ReLU: {hidden1}\n\n")
hidden1 = nn.ReLU()(hidden1)
print(f"After ReLU: {hidden1}")

Before ReLU: tensor([[ 0.0269,  0.7013,  0.4165, -0.3081,  0.6315,  0.4379,  0.0313, -0.3163,
          0.4166, -0.2110,  0.2784,  0.0810, -0.2523,  0.1916, -0.1947, -0.2500,
         -0.0333, -0.2790, -0.1866, -0.0612],
        [ 0.3003,  0.5590,  0.3479, -0.1189,  0.2572,  0.3485,  0.0308, -0.2424,
          0.1133, -0.2782,  0.0613,  0.2080, -0.0062,  0.4585, -0.4192, -0.0548,
         -0.0505, -0.0307,  0.1583, -0.2546],
        [ 0.1355,  0.5198,  0.2932, -0.3044,  0.2793,  0.0008, -0.4863, -0.3852,
          0.3688, -0.1194,  0.2554,  0.4470, -0.2893,  0.4882, -0.3769, -0.1703,
          0.0960, -0.2105, -0.1787, -0.0329]], grad_fn=<AddmmBackward0>)


After ReLU: tensor([[0.0269, 0.7013, 0.4165, 0.0000, 0.6315, 0.4379, 0.0313, 0.0000, 0.4166,
         0.0000, 0.2784, 0.0810, 0.0000, 0.1916, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000],
        [0.3003, 0.5590, 0.3479, 0.0000, 0.2572, 0.3485, 0.0308, 0.0000, 0.1133,
         0.0000, 0.0613, 0.2080, 0.0000, 0.4585, 0.00

In [21]:
seq_modules = nn.Sequential(
    flatten,
    layer1,
    nn.ReLU(),
    nn.Linear(20, 10)
)
input_image = torch.rand(3,28,28)
logits = seq_modules(input_image)

In [22]:
softmax = nn.Softmax(dim=1)
pred_probab = softmax(logits)

In [23]:
print(f"Model structure: {model}\n\n")

for name, param in model.named_parameters():
    print(f"Layer: {name} | Size: {param.size()} | Values : {param[:2]} \n")

Model structure: NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


Layer: linear_relu_stack.0.weight | Size: torch.Size([512, 784]) | Values : tensor([[-0.0182,  0.0262, -0.0004,  ..., -0.0339,  0.0297, -0.0201],
        [ 0.0122, -0.0021,  0.0041,  ...,  0.0155,  0.0221,  0.0051]],
       device='cuda:0', grad_fn=<SliceBackward0>) 

Layer: linear_relu_stack.0.bias | Size: torch.Size([512]) | Values : tensor([-0.0307,  0.0266], device='cuda:0', grad_fn=<SliceBackward0>) 

Layer: linear_relu_stack.2.weight | Size: torch.Size([512, 512]) | Values : tensor([[ 0.0225, -0.0253, -0.0418,  ...,  0.0046,  0.0038, -0.0037],
        [ 0.0152,  0.0005,  0.0246,  ..., -0.0429,  0.0245, -0.0322]],
       device='cuda:0', grad_fn=<Sl